/*
 * Swagger Delivery
 *
 * Отвечает за учет курьеров, деспетчеризацию доставкуов, доставку
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using System.Text;
using Microsoft.OpenApi.Validations;

namespace DeliveryApp.Api.Adapters.Http.Contract.src.OpenApi.Models;

/// <summary>
/// </summary>
[DataContract]
public class Courier : IEquatable<Courier>
{
    /// <summary>
    ///     Идентификатор
    /// </summary>
    /// <value>Идентификатор</value>
    [Required]
    [DataMember(Name = "id", EmitDefaultValue = false)]
    public Guid Id { get; set; }

    /// <summary>
    ///     Имя
    /// </summary>
    /// <value>Имя</value>
    [Required]
    [DataMember(Name = "name", EmitDefaultValue = false)]
    public string Name { get; set; }

    /// <summary>
    ///     Gets or Sets LocationDto
    /// </summary>
    [Required]
    [DataMember(Name = "location", EmitDefaultValue = false)]
    public Location Location { get; set; }

    /// <summary>
    ///     Returns true if CourierDto instances are equal
    /// </summary>
    /// <param name="other">Instance of CourierDto to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(Courier other)
    {
        if (other == null) 
        {
            return false;
        }

        if (ReferenceEquals(this, other)) 
        {
            return true;
        }

        var isThisLocationCorrectAndEqualsTheirLocation = Location == other.Location || (Location != null && Location.Equals(other.Location));
        var isThisNameCorrectAndEqualsTheirName = Name == other.Name || (Name != null && Name.Equals(other.Name));
        var isThisIdCorrectAndEqualsTheirId = Id == other.Id || (Id != Guid.Empty && Id.Equals(other.Id));

        return isThisLocationCorrectAndEqualsTheirLocation && isThisNameCorrectAndEqualsTheirName && isThisIdCorrectAndEqualsTheirId;
    }

    /// <summary>
    ///     Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();

        sb.Append("class CourierDto {\n");
        sb.Append("  Id: ").Append(Id).Append("\n");
        sb.Append("  Name: ").Append(Name).Append("\n");
        sb.Append("  LocationDto: ").Append(Location).Append("\n");
        sb.Append("}\n");

        return sb.ToString();
    }

    /// <summary>
    ///     Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///     Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
        if (obj == null) 
        {
            return false;
        }

        if (ReferenceEquals(this, obj)) 
        {
            return true;
        }

        return obj.GetType() == GetType() && Equals((Courier)obj);
    }

    /// <summary>
    ///     Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            // Suitable nullity checks etc, of course :)
            if (Id != Guid.Empty)
            {
                hashCode = hashCode * 59 + Id.GetHashCode();
            }

            if (Name != null) 
            {
                hashCode = hashCode * 59 + Name.GetHashCode();
            }
                
            if (Location != null)
            {
                hashCode = hashCode * 59 + Location.GetHashCode();
            }

            return hashCode;
        }
    }
    #region Operators

#pragma warning disable 1591

    public static bool operator ==(Courier left, Courier right)
    {
        return Equals(left, right);
    }

    public static bool operator !=(Courier left, Courier right)
    {
        return !Equals(left, right);
    }

#pragma warning restore 1591

    #endregion Operators
}