using DeliveryApp.Core.Domain.Model.SharedKernel;
using Xunit;

namespace DeliveryApp.UnitTests.DomainTest.Model.SharedKernel.LocationTests;

public class CreateLocationTest
{
    [Theory]
    [InlineData(1, 1)]
    [InlineData(1, 2)]
    [InlineData(1, 3)]
    [InlineData(1, 4)]
    [InlineData(1, 5)]
    [InlineData(1, 6)]
    [InlineData(1, 7)]
    [InlineData(1, 8)]
    [InlineData(1, 9)]
    [InlineData(1, 10)]
    [InlineData(2, 1)]
    [InlineData(2, 2)]
    [InlineData(2, 3)]
    [InlineData(2, 4)]
    [InlineData(2, 5)]
    [InlineData(2, 6)]
    [InlineData(2, 7)]
    [InlineData(2, 8)]
    [InlineData(2, 9)]
    [InlineData(2, 10)]
    [InlineData(3, 1)]
    [InlineData(3, 2)]
    [InlineData(3, 3)]
    [InlineData(3, 4)]
    [InlineData(3, 5)]
    [InlineData(3, 6)]
    [InlineData(3, 7)]
    [InlineData(3, 8)]
    [InlineData(3, 9)]
    [InlineData(3, 10)]
    [InlineData(4, 1)]
    [InlineData(4, 2)]
    [InlineData(4, 3)]
    [InlineData(4, 4)]
    [InlineData(4, 5)]
    [InlineData(4, 6)]
    [InlineData(4, 7)]
    [InlineData(4, 8)]
    [InlineData(4, 9)]
    [InlineData(4, 10)]
    [InlineData(5, 1)]
    [InlineData(5, 2)]
    [InlineData(5, 3)]
    [InlineData(5, 4)]
    [InlineData(5, 5)]
    [InlineData(5, 6)]
    [InlineData(5, 7)]
    [InlineData(5, 8)]
    [InlineData(5, 9)]
    [InlineData(5, 10)]
    [InlineData(6, 1)]
    [InlineData(6, 2)]
    [InlineData(6, 3)]
    [InlineData(6, 4)]
    [InlineData(6, 5)]
    [InlineData(6, 6)]
    [InlineData(6, 7)]
    [InlineData(6, 8)]
    [InlineData(6, 9)]
    [InlineData(6, 10)]
    [InlineData(7, 1)]
    [InlineData(7, 2)]
    [InlineData(7, 3)]
    [InlineData(7, 4)]
    [InlineData(7, 5)]
    [InlineData(7, 6)]
    [InlineData(7, 7)]
    [InlineData(7, 8)]
    [InlineData(7, 9)]
    [InlineData(7, 10)]
    [InlineData(8, 1)]
    [InlineData(8, 2)]
    [InlineData(8, 3)]
    [InlineData(8, 4)]
    [InlineData(8, 5)]
    [InlineData(8, 6)]
    [InlineData(8, 7)]
    [InlineData(8, 8)]
    [InlineData(8, 9)]
    [InlineData(8, 10)]
    [InlineData(9, 1)]
    [InlineData(9, 2)]
    [InlineData(9, 3)]
    [InlineData(9, 4)]
    [InlineData(9, 5)]
    [InlineData(9, 6)]
    [InlineData(9, 7)]
    [InlineData(9, 8)]
    [InlineData(9, 9)]
    [InlineData(9, 10)]
    [InlineData(10, 1)]
    [InlineData(10, 2)]
    [InlineData(10, 3)]
    [InlineData(10, 4)]
    [InlineData(10, 5)]
    [InlineData(10, 6)]
    [InlineData(10, 7)]
    [InlineData(10, 8)]
    [InlineData(10, 9)]
    [InlineData(10, 10)]
    public void WhenCreatingLocation_AndXYDontGoAboard_ThenMethodShouldBeCreateLocation(int x, int y)
    {
        //Act
        var location = Location.Create(x, y);

        //Assert
        Assert.True(location.IsSuccess);
    }

    [Theory]
    [InlineData(0, 0)]
    [InlineData(8, 0)]
    [InlineData(0, 3)]
    [InlineData(-1, 0)]
    [InlineData(0, -1)]
    [InlineData(-4, -4)]
    [InlineData(12, 12)]
    [InlineData(-34, 2)]
    [InlineData(7, 38051)]
    [InlineData(657921, 2)]
    [InlineData(8, -20531)]
    [InlineData(-529, 93091)]
    [InlineData(95023701, 2)]
    [InlineData(2, 85498701)]
    [InlineData(95023701, -93215)]
    [InlineData(95023701, 86742213)]
    [InlineData(-719529012, -1721903)]
    [InlineData(235721101, 235721101)]
    [InlineData(-1721123521, -1721123521)]
    [InlineData(int.MaxValue, int.MinValue)]
    [InlineData(int.MinValue, int.MaxValue)]
    [InlineData(int.MinValue, int.MinValue)]
    [InlineData(int.MaxValue, int.MaxValue)]

    public void WhenCreatingLocation_AndXYGoAboard_ThenMethodShouldntCreateLocation(int x, int y)
    {
        //Act
        var location = Location.Create(x, y);

        //Assert
        Assert.False(location.IsSuccess);
    }
}