/*
 * Swagger Delivery
 *
 * Отвечает за учет курьеров, деспетчеризацию доставкуов, доставку
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
*/

using DeliveryApp.Api.Adapters.Http.Contract.src.OpenApi.Attributes;
using DeliveryApp.Api.Adapters.Http.Contract.src.OpenApi.Models;
using Swashbuckle.AspNetCore.Annotations;
using Microsoft.AspNetCore.Mvc;
using DeliveryApp.Core.Application.UseCases.Queries.Dto;

namespace DeliveryApp.Api.Adapters.Http.Contract.src.OpenApi.Controllers;

/// <summary>
/// </summary>
[ApiController]
public abstract class DefaultApiController : ControllerBase
{
    [HttpPost]
    [Route("/api/v1/couriers")]
    [Consumes("application/json")]
    [ValidateModelState]
    [SwaggerOperation("CreateCourier")]
    [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Validation Error")]
    [SwaggerResponse(statusCode: 409, type: typeof(Error), description: "Buisnes logic error")]
    [SwaggerResponse(statusCode: 0, type: typeof(Error), description: "Error")]
    public abstract Task<IActionResult> CreateCourier([FromBody] CourierDto courier);

    /// <summary>
    /// Create order
    /// </summary>
    /// <remarks>Allows you to create an order for testing purposes</remarks>
    /// <response code="201">Success</response>
    /// <response code="0">Error</response>
    [HttpPost]
    [Route("/api/v1/orders")]
    [ValidateModelState]
    [SwaggerOperation("CreateOrder")]
    [SwaggerResponse(0, type: typeof(Error), description: "Error")]
    public abstract Task<IActionResult> CreateOrder();

    /// <summary>
    /// Get all not busy couriers
    /// </summary>
    /// <remarks>Allows you to get all couriers</remarks>
    /// <response code="200">Success</response>
    /// <response code="0">Error</response>
    [HttpGet]
    [Route("/api/v1/couriers/")]
    [ValidateModelState]
    [SwaggerOperation("GetAllCouriers")]
    [SwaggerResponse(200, type: typeof(List<Courier>), description: "Success")]
    [SwaggerResponse(0, type: typeof(Error), description: "Error")]
    public abstract Task<IActionResult> GetCouriers();

    /// <summary>
    /// Get all active orders
    /// </summary>
    /// <remarks>Allows you to get all unfinished</remarks>
    /// <response code="200">Success</response>
    /// <response code="0">Error</response>
    [HttpGet]
    [Route("/api/v1/orders/active")]
    [ValidateModelState]
    [SwaggerOperation("GetOrders")]
    [SwaggerResponse(200, type: typeof(List<Order>), description: "Success")]
    [SwaggerResponse(0, type: typeof(Error), description: "Error")]
    public abstract Task<IActionResult> GetOrders();
}