/*
 * Swagger Delivery
 *
 * Отвечает за учет курьеров, диспетчеризацию доставок, доставку
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using DeliveryApp.Api.Adapters.Http.Contract.OpenApi.Attributes;
using DeliveryApp.Api.Adapters.Http.Contract.OpenApi.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;

namespace DeliveryApp.Api.Adapters.Http.Contract.OpenApi.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class CompleteOrderApiController : ControllerBase
    { 
        /// <summary>
        /// Завершить заказ
        /// </summary>
        /// <remarks>Позволяет завершить заказ</remarks>
        /// <param name="courierId">Идентификатор курьера</param>
        /// <param name="orderId">Идентификатор заказа</param>
        /// <response code="200">Успешный ответ</response>
        /// <response code="400">Некорректные параметры запроса</response>
        /// <response code="409">Конфликт при завершении заказа</response>
        /// <response code="500">Внутренняя ошибка сервиса</response>
        [HttpPost]
        [Route("/api/v1/couriers/{courierId}/orders/{orderId}/complete")]
        [ValidateModelState]
        [SwaggerOperation("CompleteOrder")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректные параметры запроса")]
        [SwaggerResponse(statusCode: 409, type: typeof(Error), description: "Конфликт при завершении заказа")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервиса")]
        public virtual Task<IActionResult> CompleteOrder([FromRoute (Name = "courierId")][Required]Guid courierId, [FromRoute (Name = "orderId")][Required]Guid orderId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default);
            //TODO: Uncomment the next line to return response 409 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(409, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);

            throw new NotImplementedException();
        }
    }
}
