/*
 * Swagger Delivery
 *
 * Отвечает за учет курьеров, диспетчеризацию доставок, доставку
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using DeliveryApp.Api.Adapters.Http.Contract.OpenApi.Attributes;
using DeliveryApp.Api.Adapters.Http.Contract.OpenApi.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.AspNetCore.Annotations;

namespace DeliveryApp.Api.Adapters.Http.Contract.OpenApi.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class CreateCourierApiController : ControllerBase
    { 
        /// <summary>
        /// Добавить курьера
        /// </summary>
        /// <remarks>Позволяет добавить курьера</remarks>
        /// <param name="newCourier">Курьер</param>
        /// <response code="201">Курьер успешно создан</response>
        /// <response code="400">Некорректные параметры запроса</response>
        /// <response code="409">Конфликт при создании курьера</response>
        /// <response code="500">Внутренняя ошибка сервиса</response>
        [HttpPost]
        [Route("/api/v1/couriers")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateCourier")]
        [SwaggerResponse(statusCode: 201, type: typeof(CreateCourierResponse), description: "Курьер успешно создан")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректные параметры запроса")]
        [SwaggerResponse(statusCode: 409, type: typeof(Error), description: "Конфликт при создании курьера")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервиса")]
        public virtual Task<IActionResult> CreateCourier([FromBody]NewCourier newCourier)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default);
            //TODO: Uncomment the next line to return response 409 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(409, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "{\r\n  \"courierId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\"\r\n}";
            exampleJson = "{\r\n  \"code\" : 0,\r\n  \"message\" : \"message\"\r\n}";
            exampleJson = "{\r\n  \"code\" : 0,\r\n  \"message\" : \"message\"\r\n}";
            exampleJson = "{\r\n  \"code\" : 0,\r\n  \"message\" : \"message\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<CreateCourierResponse>(exampleJson)
            : default;
            //TODO: Change the data returned
            return Task.FromResult<IActionResult>(new ObjectResult(example));
        }
    }
}
