/*
 * Swagger Delivery
 *
 * Отвечает за учет курьеров, диспетчеризацию доставок, доставку
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using DeliveryApp.Api.Adapters.Http.Contract.OpenApi.Attributes;
using DeliveryApp.Api.Adapters.Http.Contract.OpenApi.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.AspNetCore.Annotations;

namespace DeliveryApp.Api.Adapters.Http.Contract.OpenApi.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class GetCouriersApiController : ControllerBase
    { 
        /// <summary>
        /// Получить всех курьеров
        /// </summary>
        /// <remarks>Позволяет получить всех курьеров</remarks>
        /// <response code="200">Успешный ответ</response>
        /// <response code="400">Некорректные параметры запроса</response>
        /// <response code="500">Внутренняя ошибка сервиса</response>
        [HttpGet]
        [Route("/api/v1/couriers")]
        [ValidateModelState]
        [SwaggerOperation("GetCouriers")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Courier>), description: "Успешный ответ")]
        [SwaggerResponse(statusCode: 400, type: typeof(Error), description: "Некорректные параметры запроса")]
        [SwaggerResponse(statusCode: 500, type: typeof(Error), description: "Внутренняя ошибка сервиса")]
        public virtual Task<IActionResult> GetCouriers()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default);
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400, default);
            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500, default);
            string exampleJson = null;
            exampleJson = "[ {\r\n  \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"name\" : \"name\",\r\n  \"location\" : \"\"\r\n}, {\r\n  \"id\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\",\r\n  \"name\" : \"name\",\r\n  \"location\" : \"\"\r\n} ]";
            exampleJson = "{\r\n  \"code\" : 0,\r\n  \"message\" : \"message\"\r\n}";
            exampleJson = "{\r\n  \"code\" : 0,\r\n  \"message\" : \"message\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<Courier>>(exampleJson)
            : default;
            //TODO: Change the data returned
            return Task.FromResult<IActionResult>(new ObjectResult(example));
        }
    }
}
